permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "刁爷"
email: 805386312@qq.com
description: ""
github:
  username: lvkss2012
swiftype:
  searchId: ycwD8pEs_X6sQp39PtDY
gitment:
    repo: blog
    client_id: 3baed82bb6e0df56154d
    client_secret: 189f679b7c4269fd50fde92bc8dbdf2277e9ca03

url: "https://lvkss2012.github.io/blog"
imgrepo: "https://lvkss2012.github.io/blog/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

